version: '3.8'

services:

  mongodb:
    image: mongo:7.0.9
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - ./data/mongodb:/data/db
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 1s
      retries: 10

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: rootpassword
  
  mysqldb:
    image: mysql:8.4.0
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fastapi
    volumes:
      - ./data/mysqldb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 1s
      retries: 10
  
  # fast-api:
  #   build: .
  #   image: fast_base
  #   container_name: fast_api
  #   restart: unless-stopped
  #   depends_on:
  #     - mongodb
  #     - mongo-express
  #     - mysqldb
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - .:/app
  #   environment:
  #     MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
  #     MYSQL_URL: mysql+pymysql://root:rootpassword@mysqldb:3306/fastapi
  #     ASYNC_MYSQL_URL: mysql+aiomysql://root:rootpassword@mysqldb:3306/fastapi
  #   command: sh -c "until nc -z -w 1 mysqldb 3306; do sleep 1; done && uvicorn main:app --reload --host 0.0.0.0 --port 8000"